// Country code -> best Wikipedia article title to source a representative photo from.
// Mostly capital cities (nicer skyline/landmark photos than a flag), with a few
// exceptions where a different article is more reliable (disambiguation, tiny
// territories with sparse capital-article photos, etc).
export const PHOTO_SOURCE_TITLE = {
  AFG: "Kabul", ALB: "Tirana", DZA: "Algiers", AND: "Andorra la Vella", AGO: "Luanda",
  ARG: "Buenos Aires", ARM: "Yerevan", ABW: "Oranjestad", AUT: "Vienna",
  AZE: "Baku", BHS: "Nassau, Bahamas", BHR: "Manama", BGD: "Dhaka", BLR: "Minsk",
  BEL: "Brussels", BLZ: "Belmopan", BEN: "Porto-Novo", BTN: "Thimphu", BOL: "La Paz",
  BIH: "Sarajevo", BWA: "Gaborone", BRA: "Rio de Janeiro", BRN: "Bandar Seri Begawan",
  BGR: "Sofia", BFA: "Ouagadougou", BDI: "Bujumbura", KHM: "Phnom Penh", CMR: "Yaoundé",
  CAN: "Toronto", CPV: "Praia", CAF: "Bangui", TCD: "N'Djamena", CHL: "Santiago",
  CHN: "Shanghai", COL: "Bogotá", COM: "Moroni, Comoros", COG: "Brazzaville", COD: "Kinshasa",
  CRI: "San José, Costa Rica", CIV: "Abidjan", HRV: "Dubrovnik", CUW: "Willemstad",
  CYP: "Nicosia", CZE: "Prague", DNK: "Copenhagen", DJI: "Djibouti City", DMA: "Roseau",
  DOM: "Santo Domingo", ECU: "Quito", SLV: "San Salvador", EST: "Tallinn",
  SWZ: "Mbabane", ETH: "Addis Ababa", FRO: "Tórshavn", FJI: "Suva", FIN: "Helsinki",
  GUF: "Cayenne", PYF: "Papeete", GAB: "Libreville", GMB: "Banjul", GEO: "Tbilisi",
  GHA: "Accra", GIB: "Europa Point", GRC: "Athens", GRL: "Nuuk", GLP: "Pointe-à-Pitre",
  GUM: "Hagåtña, Guam", GTM: "Antigua Guatemala", GIN: "Conakry",
  GNB: "Bissau", GUY: "Georgetown, Guyana", HND: "Tegucigalpa", HKG: "Central, Hong Kong",
  HUN: "Budapest", ISL: "Reykjavík", IND: "Mumbai", IDN: "Bali", IRQ: "Baghdad",
  IRL: "Dublin", ISR: "Tel Aviv", ITA: "Venice", JAM: "Kingston, Jamaica", JOR: "Amman",
  KAZ: "Astana", KEN: "Nairobi", XKX: "Pristina", KWT: "Kuwait City", KGZ: "Bishkek",
  LVA: "Riga", LTU: "Vilnius", LUX: "Luxembourg City", MAC: "Senado Square", MKD: "Skopje",
  MDG: "Antananarivo", MWI: "Lilongwe", MYS: "Kuala Lumpur", MLI: "Bamako",
  MLT: "Valletta", MTQ: "Fort-de-France", MRT: "Nouakchott", MUS: "Port Louis",
  MYT: "Mamoudzou", MDA: "Chișinău", MNG: "Ulaanbaatar", MNE: "Kotor",
  MOZ: "Maputo", NAM: "Windhoek", NRU: "Yaren", NPL: "Kathmandu", NLD: "Amsterdam",
  NCL: "Nouméa", NZL: "Auckland", NIC: "Managua", NGA: "Lagos", NOR: "Oslo",
  OMN: "Muscat", PAK: "Lahore", PSE: "Ramallah", PAN: "Panama City", PRY: "Asunción",
  PER: "Lima", PHL: "Manila", POL: "Warsaw", PRT: "Lisbon", PRI: "San Juan, Puerto Rico",
  ROU: "Bucharest", RUS: "Moscow", RWA: "Kigali", BLM: "Gustavia", MAF: "Marigot, Saint Martin",
  WSM: "Apia", SEN: "Dakar", SRB: "Belgrade", SYC: "Victoria, Seychelles",
  SLE: "Freetown", SGP: "Singapore", SVK: "Bratislava", SVN: "Ljubljana",
  SSD: "Juba", SDN: "Khartoum", SUR: "Paramaribo", SWE: "Stockholm", CHE: "Zurich",
  TWN: "Taipei", TJK: "Dushanbe", TZA: "Zanzibar City", TGO: "Lomé", TON: "Nukuʻalofa",
  TTO: "Port of Spain", TUN: "Tunis", UGA: "Kampala", UKR: "Kyiv", URY: "Montevideo",
  UZB: "Tashkent", VEN: "Caracas", VNM: "Hanoi", VGB: "Road Town",
  VIR: "Charlotte Amalie", ZMB: "Lusaka",
  GBR: "London", USA: "New York City",
  REU: "Saint-Denis, Réunion", LKA: "Colombo", VUT: "Port Vila",
};
