// Builds the SQL that loads our eSIM stock into sim_inventory and marks the
// CSO_7434 delivery as physical SIMs. Read-only towards Transatel (GET
// requests only, via scripts/lib/transatel-readonly.mjs); writes a .sql
// file for you to run once in phpMyAdmin — it never connects to MySQL.
//
// Usage:
//   npm run esims:import-sql -- <output.sql>
//
// Save the output OUTSIDE the repo (e.g. your Downloads folder): it lists
// ICCIDs and MSISDNs. It never contains activation codes.
//
// An eSIM is imported only if it is usable for a new customer:
//   - not in the CSO_7434 delivery file (those 1,000 are physical cards),
//   - SIM status Pre-Activated in SIM Search,
//   - eSIM profile "released" with an activation code (our account can't
//     release profiles itself), and not bound to a device (no EID).
// Everything else is listed with the reason it was left out.
import fs from "node:fs";
import { api, authenticate, errorSummary, readPhysicalDeliveryIccids, searchAllSims } from "./lib/transatel-readonly.mjs";

const outPath = process.argv[2];
if (!outPath) {
  console.error("Usage: npm run esims:import-sql -- <output.sql>   (save it outside the repo)");
  process.exit(1);
}

const sqlString = (value) => `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "''")}'`;
const digitsOnly = (msisdn) => String(msisdn ?? "").replace(/\D/g, "");

const auth = await authenticate();
if (!auth.ok) {
  console.error(`Authentication failed (HTTP ${auth.status}). Check the TRANSATEL_* values in .env.local.`);
  process.exit(1);
}

const physicalIccids = await readPhysicalDeliveryIccids();
const physicalSet = new Set(physicalIccids);
const { sims, error } = await searchAllSims();
if (error) {
  console.error(`SIM Search failed: ${error}`);
  process.exit(1);
}
console.log(`SIMs on the account: ${sims.length}. Physical (CSO_7434 file): ${physicalIccids.length}.`);

const missingPhysical = physicalIccids.filter((iccid) => !sims.some((s) => s.simSerial === iccid));
if (missingPhysical.length) console.warn(`Warning: ${missingPhysical.length} CSO_7434 ICCIDs are not on the account, e.g. ${missingPhysical.slice(0, 3).join(", ")}`);

const candidates = sims.filter((s) => !physicalSet.has(s.simSerial));
console.log(`eSIM candidates (not in the CSO_7434 file): ${candidates.length}. Checking each eSIM profile…`);

const usable = [];
const excluded = [];
let checked = 0;
const queue = [...candidates];
async function worker() {
  for (let sim = queue.shift(); sim; sim = queue.shift()) {
    const reason = await unusableReason(sim);
    if (reason) excluded.push({ iccid: sim.simSerial, reason });
    else usable.push({ iccid: sim.simSerial, msisdn: digitsOnly(sim.msisdn), status: sim.status });
    checked++;
    if (checked % 50 === 0) console.log(`  ${checked}/${candidates.length}`);
  }
}

async function unusableReason(sim) {
  if (!/^pre-?activated$/i.test(String(sim.status ?? "").trim())) return `SIM status "${sim.status}" (not Pre-Activated)`;
  if (!/^[0-9]{6,15}$/.test(digitsOnly(sim.msisdn))) return "no valid MSISDN in SIM Search";
  const r = await api("GET", `/sim-management/sims/api/esims/sim-serial/${sim.simSerial}`);
  if (r.status === 404) return "not an eSIM (Unknown eSIM)";
  if (r.status !== 200) return `Get eSIM details failed: HTTP ${r.status} ${errorSummary(r)}`;
  if (r.body.status !== "released") return `eSIM profile "${r.body.status}" (not released)`;
  if (!r.body.activationCode) return "no activation code";
  if (r.body.eid) return "eSIM profile bound to a device (EID present)";
  return null;
}

// A few requests at a time: quicker than one-by-one, gentle on Transatel.
await Promise.all(Array.from({ length: 4 }, worker));
usable.sort((a, b) => a.iccid.localeCompare(b.iccid));

const now = new Date().toISOString().slice(0, 19).replace("T", " ");
const lines = [
  `-- Generated by scripts/import-esims.mjs at ${now} UTC.`,
  "-- Contains ICCIDs and MSISDNs (no activation codes). Run once in phpMyAdmin on the production database.",
  "START TRANSACTION;",
  "",
  `-- 1. The ${physicalIccids.length} SIMs from delivery CSO_7434 are physical cards, never sold as eSIMs.`,
  `UPDATE sim_inventory SET sim_type = 'physical' WHERE iccid IN (${physicalIccids.map(sqlString).join(", ")});`,
  "",
];
if (usable.length) {
  lines.push(
    `-- 2. ${usable.length} usable eSIMs: Pre-Activated, profile released with an activation code, not bound to a device.`,
    "INSERT INTO sim_inventory (iccid, msisdn, sim_type, transatel_hlr_status, is_activated, status, created_at) VALUES",
    usable
      .map((s) => `  (${sqlString(s.iccid)}, ${sqlString(s.msisdn)}, 'esim', ${sqlString(s.status)}, 0, 'available', ${sqlString(now)})`)
      .join(",\n"),
    "ON DUPLICATE KEY UPDATE msisdn = VALUES(msisdn), sim_type = 'esim';",
    ""
  );
}
lines.push(
  "COMMIT;",
  "",
  "-- Check afterwards (expect physical/available and esim/available counts matching the above):",
  "-- SELECT sim_type, status, COUNT(*) FROM sim_inventory GROUP BY sim_type, status;"
);
fs.writeFileSync(outPath, lines.join("\n") + "\n");

console.log(`\nUsable eSIMs: ${usable.length}. Left out: ${excluded.length}.`);
for (const e of excluded) console.log(`  ${e.iccid}: ${e.reason}`);
console.log(`\nWrote ${outPath}. Review it, then run it in phpMyAdmin (SQL tab) on the production database.`);
